apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-user: bW9uZ291c2Vy  # Base64 encoded username (mongouser)
  mongodb-password: bW9uZ29wYXNzMTIz  # Base64 encoded password (mongopass123)
