apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: vyshnavinerella25/diabetes:tag3 # Replace with your actual image
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-user  # MongoDB username from the Secret
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password  # MongoDB password from the Secret
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongodb-url  # MongoDB service URL from the ConfigMap

